<footer>
	<div class="container-fluid">
		<div class="row">
			<div class="col-xs-12 col-md-4">
				<h4><?= ACERCA_DE ?></h4>
				&copy; <?= date("Y") ?> Vampiria Software <br>
				<?= DERECHOS ?>
			</div>
			<div class="col-xs-12 col-md-4">
				<h4><?= CONTACTO ?></h4>
				<span class="fa fa-envelope"></span> <a href="mailto:info@vampiriasoftware.tk">info@vampiriasoftware.tk</a><br>
				<span class="fa fa-phone"></span> 045 (749) 103 89 43 <br>
			</div>
			<div class="col-xs-12 col-md-4">
				<h4><?= SIGUENOS ?></h4>
				<a class="ayuda" href="http://www.facebook.com/VampiriaSoftware" target="_blank" title="Facebook">
					<span class="fa fa-facebook fa-3x"></span>
				</a>

				<a class="ayuda" href="https://twitter.com/VampiriaSoft/" target="_blank" title="Twitter">
					<span class="fa fa-twitter fa-3x"></span>
				</a>
			</div>
		</div>
	</div><br>
</footer>