<!-- barra de menu -->
<header>
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container-fluid">
			<div class="navbar-header">
				<button class="navbar-toggle" data-toggle="collapse" data-target="#navegacion">
					<span class="sr-only">Menu</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a href="<?= BASEURL ?>" class="navbar-brand">
					<img src="<?= BASEURL ?>public/images/logo.png" alt="Vampiria Software">
				</a>
			</div>
			<div class="collapse navbar-collapse" id="navegacion">
				<ul class="nav navbar-nav">
					<li><a href="<?= BASEURL ?>nosotros/"><?= QUIENES ?></a></li>
					<li><a href="<?= BASEURL ?>servicios/"><?= SERVICIOS ?></a></li>
					<li><a href="<?= BASEURL ?>portafolio/"><?= PORTAFOLIO ?></a></li>
					<li><a href="<?= BASEURL ?>contacto/"><?= CONTACTO ?></a></li>
				</ul>
				<!--<ul class="nav navbar-nav navbar-right">
					<li><a href="javascript:void(0);"><?= LOGIN ?></a></li>
					<li><a href="<?= BASEURL ?>usuarios/registro/"><?= REGISTRARME ?></a></li>
					<li class="dropdown">
						<a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
							<img src="<?= BASEURL ?>public/images/spanish.png" alt="Español" height="20">
							<b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li>
								<a href="">
									<img src="<?= BASEURL ?>public/images/spanish.png" alt="Español" height="20"> Español
								</a>
							</li>
							<li>
								<a href="">
									<img src="<?= BASEURL ?>public/images/english.png" alt="English" height="20"> English
								</a>
							</li>
						</ul>
					</li>
				</ul>-->
			</div>
		</div>
	</nav>
</header>
<!-- fin barra de menu -->