<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head prefix="og: http://ogp.me/ns#">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Vampiria Software</title>
        <meta name="description" content="Vampiria Software es una empresa mexicana que nace a principios del mes de Abril del año 2013 con la finalidad de brindar soluciones empresariales de la mejor calidad." >
        <meta name="keywords" content="Vampiria Software,software,aplicaciones web,php,javascript,css,mysql,base de datos,blog,joomla,wordpress,c++,c#,python,ruby,ruby on rails,diseño web,maquetación web,django,jquery,ajax,android,uml,analisis,diseño,objetos,programación,asp,visual basic,.net,servicios web,carrito de compras,soluciones empresariales,sistemas a la medida,html5,juegos,cursos,ios,aplicaciones moviles" >
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta property="og:url" content="http://www.vampiriasoftware.tk/" > 
        <meta property="og:site_name" content="Vampiria Software" > 
        <meta property="og:title" content="Vampiria Software" > 
        <meta property="og:description" content="Vampiria Software es una empresa mexicana que nace a principios del mes de Abril del año 2013 con la finalidad de brindar soluciones empresariales de la mejor calidad." >
        <meta property="og:image" content="http://vampiriasoftware.tk/public/images/img_fb.jpg" >
        <link rel="shortcut icon" href="<?= BASEURL; ?>public/images/favicon.ico" />

        <link rel="stylesheet" href="<?= BASEURL ?>public/css/normalize.css">
        <link rel="stylesheet" href="<?= BASEURL ?>public/css/default.css">
        <script src="<?= BASEURL ?>public/js/lib/modernizr-2.6.2.min.js"></script>
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        <?php require_once BASEPATH . 'application/layout/controller/header.php'; ?>
        <div class="container-fluid contenido">
            <ol class="breadcrumb">
                <li><a href="<?= BASEURL ?>"><span class="fa fa-home"></span></a></li>
                <li class="active"><?= SERVICIOS ?></li>
            </ol>
            <section class="col-xs-12 col-md-12">
                <h2><?= SERVICIOS ?></h2>
                <div class="row">
                    <div class="col-xs-12 col-md-4">
                        <h3><?= DISENO ?></h3>
                        <p>
                            <?= DISENO_CONTENIDO ?>
                        </p>
                        <span class="fa fa-css3 fa-5x"></span> 
                        <span class="fa fa-joomla fa-5x"></span>
                        <span class="fa fa-wordpress fa-5x"></span>
                        <span class="fa fa-html5 fa-5x"></span>
                    </div>
                    <div class="col-xs-12 col-md-4">
                        <h3><?= DESARROLLO ?></h3>
                        <p>
                            <?= DESARROLLO_CONTENIDO ?>
                        </p>
                        <span class="fa fa-code fa-5x"></span>
                    </div>
                    <div class="col-xs-12 col-md-4">
                        <h3><?= APPS ?></h3>
                        <p>
                            <?= APPS_CONTENIDO ?>
                        </p>
                        <span class="fa fa-android fa-5x"></span>
                        <span class="fa fa-apple fa-5x"></span>
                        <span class="fa fa-windows fa-5x"></span>
                    </div>
                </div>
            </section>
        </div>
        <?php require_once BASEPATH . 'application/layout/controller/footer.php'; ?>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="<?= BASEURL ?>public/js/lib/jquery-1.10.2.min.js"><\/script>')</script>
        <script src="<?= BASEURL ?>public/js/lib/bootstrap.min.js"></script>
        <script src="<?= BASEURL ?>public/js/scrollUp.min.js"></script>
        <script>
            var url = '<?= BASEURL ?>';
        </script>
        <script src="<?= BASEURL ?>public/js/language/<?= $language ?>.js"></script>
        <script src="<?= BASEURL ?>application/usuarios/js/Usuarios.js"></script>
        <script src="<?= BASEURL ?>public/js/main.js"></script>

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-44883526-1');ga('send','pageview');
        </script>
    </body>
</html>
